### ISSUE TITLE
蓝牙可以唤醒电脑吗

### ISSUE THREAD

**Issue by cattyhouse** [kennydiff/B360M-HDV_Hackin#1]
我也是这块主板, 用的是943602CS的 PCIe的网卡, 蓝牙键盘无法唤醒黑苹果. 除此之外, 都完美.

**Comment by tpfortree** [comment]
弃坑，，，白苹果伺候，，，我性格太追求完美，黑苹果简直找罪。 不浪费时间了。

**Comment by tpfortree** [comment]
蓝牙无法唤醒，蓝牙键盘可以唤醒我的mbp

**Comment by cattyhouse** [comment]
> 蓝牙无法唤醒，蓝牙键盘可以唤醒我的mbp

我这边也是无法唤醒, 我是淘宝小齐本本买的Wi-Fi卡. 我觉得这个卡有毛病. 其余完美呀, 试试OpenCore. 你可以参考我的github上的文档, 我现在 10.15 beta 10 , 完美的一笔.
